import type { Alpine } from 'alpinejs';

const components: Record<string, () => Promise<any>> = {
  layout: () => import('@/Layouts/layoutLogic'),
  navbar: () => import('@/components/common/navbarLogic'),
  articleList: () => import('@/components/dashboard/articleListLogic'),
  flipperList: () => import('@/components/dashboard/flipperListLogic'),
  profile: () => import('@/components/profile/profileLogic'),
  calendar: () => import('@/components/calendar/logic'),
  articleCreator: () => import('@/components/article/creatorLogic'),
  flipperCreator: () => import('@/components/dashboard/flipperCreatorLogic'),
  eventCreator: () => import('@/components/article/eventCreatorLogic'),
  eventList: () => import('@/components/dashboard/eventListLogic'),
  authModal: () => import('@/components/auth/authLogic'),
  contentActions: () => import('@/components/common/contentActionsLogic'),
  interviewList: () => import('@/components/dashboard/interviewListLogic'),
  interviewCreator: () => import('@/components/dashboard/interviewCreatorLogic'),
  newsCreator: () => import('@/components/dashboard/newsCreatorLogic'),
  newsList: () => import('@/components/dashboard/newsListLogic'),
  subscriptionManager: () => import('@/components/profile/subscriptionLogic'),
  tipsArticleCreator: () => import('@/components/dashboard/tipsArticleCreatorLogic'),
  tipsList: () => import('@/components/dashboard/tipsListLogic'),
  leSaviezVousList: () => import('@/components/dashboard/leSaviezVousListLogic'),
  landingEditor: () => import('@/components/dashboard/landingEditorLogic'),
  calendarEditor: () => import('@/components/dashboard/calendarEditorLogic'),
  cultureEditor: () => import('@/components/dashboard/cultureEditorLogic'),
  parisEditor: () => import('@/components/dashboard/parisEditorLogic'),
  guideCreator: () => import('@/components/article/guideCreatorLogic'),
  guideList: () => import('@/components/dashboard/guideListLogic'),
  visualStoryCreator: () => import('@/components/article/visualStoryCreatorLogic'),
  visualStoryList: () => import('@/components/dashboard/visualStoryListLogic'),
  photoOfTheDayCreator: () => import('@/components/dashboard/photoOfTheDayCreatorLogic'),
  photoOfTheDayList: () => import('@/components/dashboard/photoOfTheDayListLogic'),
};

export default function(Alpine: Alpine) {
  Alpine.magic('lazy', () => (name: string, initialState: object) => {
    return {
      isLazyLoading: true,
      init() {
        const importer = components[name];
        if (!importer) {
          console.error(`[Lazy Plugin] Importer for ${name} not found.`);
          return;
        }

        return importer()
          .then(module => {
            const data = module.default(initialState);
            
            // Extract the loaded module's init function, if it exists
            const newInit = data.init;
            
            // Remove init from the data object to avoid conflicts/recursion
            delete data.init;

            Object.assign(this, data);
            
            // If the loaded module had an init, call it now
            if (typeof newInit === 'function') {
              newInit.call(this);
            }

            this.$nextTick(() => {
              this.isLazyLoading = false;
            });
          })
          .catch(err => {
            console.error(`[Lazy Plugin] Error during lazy-load of ${name}`, err);
          });
      },
      // Provide a full skeleton to prevent errors
      // --- Calendar properties ---
      selectedDate: null,
      rangeStartDate: null,
      rangeEndDate: null,
      hoverDate: null,
      isRangeSelecting: false,
      year: 0,
      month: 0,
      monthName: '...',
      daysInMonth: 0,
      firstDayOfMonth: 0,
      calendarDays: [],
      events: [],
      featuredEvents: [],
      filters: [],
      activeFilter: 'все',
      activeFeaturedIndex: 0,
      isFeaturedEventVisible: true,
      featuredAutoplayIntervalMs: 4500,
      featuredAutoplayResumeDelayMs: 8000,
      featuredAutoplayTimer: null,
      featuredAutoplayResumeTimer: null,
      featuredEventTransitionTimer: null,
      isFeaturedHovered: false,
      isFeaturedFocused: false,
      isFeaturedAutoplayPausedByUser: false,
      prefersReducedMotion: false,
      featuredVisibilityHandler: null,
      updateCalendarDisplay() {},
      buildCalendarDays() { return []; },
      resolveCalendarDate() { return new Date(); },
      getDefaultDateForMonth() { return new Date(); },
      changeMonth() {},
      selectDate() {},
      hasEvent() { return false; },
      setFilter() {},
      isSameDay() { return false; },
      hasCompletedRange() { return false; },
      setHoverDate() {},
      clearHoverDate() {},
      isInHoverMode() { return false; },
      isHoverEnd() { return false; },
      isHoverRangeStart() { return false; },
      isHoverRangeEnd() { return false; },
      isWithinHoverRange() { return false; },
      isSelectedDate() { return false; },
      isRangeStart() { return false; },
      isRangeEnd() { return false; },
      isRangeBoundary() { return false; },
      isWithinSelectedRange() { return false; },
      getSelectedDateHeading() { return ''; },
      updateFilteredEvents() {},
      getCurrentFeaturedEvent() { return null; },
      hasMultipleFeaturedEvents() { return false; },
      canAutoplayFeaturedEvents() { return false; },
      startFeaturedAutoplay() {},
      stopFeaturedAutoplay() {},
      updateFeaturedAutoplayState() {},
      pauseFeaturedAutoplayTemporarily() {},
      setFeaturedHover() {},
      setFeaturedFocus() {},
      switchFeaturedEvent() {},
      prevFeaturedEvent() {},
      nextFeaturedEvent() {},
      destroy() {},
      filteredEvents: [],
      smallEvents: [],
      availableEventsCount: 0,
      // --- Article Creator properties ---
      article: {
        title: '',
        lead: '',
        cardLead: '',
        articleType: 'standard',
        imageUrl: '',
        imageCaption: '',
        contentBlocks: [],
        tags: [],
        parisSubCategories: [],
        parisDistrict: '',
        binaryForGuide: false,
        tips: [],
        category: '',
        isHotContent: false,
        isMainInCategory: false,
        paid: false,
        published: false,
        publishedAt: null,
        contentCollectionId: null,
        relatedContent: {
          article: [],
          event: [],
          interview: [],
          guide: [],
          news: [],
          flipper: [],
          visualStory: [],
        },
      },
      // --- Interview Creator properties ---
      interview: {
        title: '',
        interviewee: '',
        lead: '',
        cardLead: '',
        mainQuote: '',
        isHotContent: false,
        paid: false,
        published: false,
        publishedAt: null,
        imageUrl: '',
        imageCaption: '',
        contentBlocks: [],
        tags: [],
        relatedContent: {
          article: [],
          event: [],
          interview: [],
          guide: [],
          news: [],
          flipper: [],
          visualStory: [],
        },
      },
      showBlockOptions: false,
      editingIndex: null,
      editingBlock: null,
      isEditingTitle: false,
      editingTitleText: '',
      isEditingCaption: false,
      editingCaptionText: '',
      uploading: false,
      uploadProgress: 0,
      isSaving: false,
      categoryTags: {},
      articleId: null,
      isEditMode: false,
      onSaveRedirect: null,
      categoryLabels: {},
      contentListsLoading: false,
      landingPlacements: {
        schemaVersion: 2,
        mainHero: null,
        newsRail: {
          mode: 'auto-latest',
          limit: 4,
        },
        netlenkaRail: {
          mode: 'auto-latest',
          limit: 4,
        },
        eventCard: {
          mode: 'auto-nearest',
        },
        cultureInterviewBlock: {
          mode: 'auto-latest',
        },
        updatedAt: null,
        updatedBy: null,
      },
      placementLoading: false,
      placementSaving: false,
      placementError: '',
      currentMainHeroTitle: '',
      mainHeroOptions: [],
      mainHeroMode: 'empty',
      selectedMainHeroType: '',
      selectedMainHeroArticleBucket: '',
      selectedMainHeroKey: '',
      mainHeroSaving: false,
      mainHeroError: '',
      cultureHeroOptions: [],
      cultureHeroMode: 'empty',
      selectedCultureHeroKey: '',
      cultureHeroSaving: false,
      cultureHeroError: '',
      saveCultureHero() {},
      parisHeroOptions: [],
      parisHeroMode: 'empty',
      selectedParisHeroKey: '',
      parisHeroSaving: false,
      parisHeroError: '',
      saveParisHero() {},
      newsOptions: [],
      newsRailMode: 'auto-latest',
      newsRailLimit: 4,
      selectedNewsIds: [],
      newsSaving: false,
      newsError: '',
      netlenkaOptions: [],
      netlenkaRailMode: 'auto-latest',
      netlenkaRailLimit: 4,
      selectedNetlenkaKeys: [],
      netlenkaSaving: false,
      netlenkaError: '',
      isManualNetlenkaSelected() { return false; },
      toggleNetlenkaItem() {},
      saveNetlenkaRail() {},
      cultureCardsOptions: [],
      cultureCardsMode: 'auto-latest',
      cultureCardsLimit: 3,
      selectedCultureCardKeys: [],
      cultureCardsSaving: false,
      cultureCardsError: '',
      isManualCultureCardSelected() { return false; },
      toggleCultureCardItem() {},
      saveCultureCards() {},
      parisCardsOptions: [],
      parisCardsMode: 'auto-latest',
      parisCardsLimit: 3,
      selectedParisCardKeys: [],
      parisCardsSaving: false,
      parisCardsError: '',
      isManualParisCardSelected() { return false; },
      toggleParisCardItem() {},
      saveParisCards() {},
      eventOptions: [],
      eventCardMode: 'auto-nearest',
      selectedEventId: '',
      eventSaving: false,
      eventError: '',
      interviewOptions: [],
      cultureInterviewMode: 'auto-latest',
      selectedInterviewId: '',
      cultureInterviewSaving: false,
      cultureInterviewError: '',
      relatedContentLists: {
        article: [],
        event: [],
        interview: [],
        guide: [],
        news: [],
        flipper: [],
        visualStory: [],
      },
      relatedContentTypeOptions: [],
      selectedRelatedContentType: 'article',
      selectedRelatedContentId: '',
      contentCollectionsLoading: false,
      availableContentCollections: [],
      contentCollection: null,
      selectedContentCollectionId: '',
      useNewContentCollection: false,
      newContentCollectionTitle: '',
      tipOptions: [],
      authorsLoading: false,
      authors: [],
      selectedAuthorId: '',
      useNewAuthor: false,
      newAuthorFirstName: '',
      newAuthorLastName: '',
      getCategoryLabel() { return 'Category'; },
      getAvailableTags() { return []; },
      getSelectedCategoryTags() { return []; },
      getTagLabel(value: string) { return value; },
      getAuthorLabel() { return ''; },
      getUiStore() { return null; },
      notify() {},
      isTagSelected() { return false; },
      toggleTag() {},
      removeTag() {},
      isTipSelected() { return false; },
      toggleTip() {},
      getTipText() { return ''; },
      setTipText() {},
      getTipUrl() { return ''; },
      setTipUrl() {},
      loadAuthors() {},
      syncCurrentContentCollection() {},
      loadContentCollections() {},
      assignSelectedContentCollection() {},
      createAndAssignContentCollection() {},
      removeContentCollection() {},
      resolveAuthorId() { return ''; },
      handleCategoryChange() {},
      handleImageUpload() {},
      openBlockSelector() {},
      addBlock() {},
      editBlock() {},
      updateBlock() {},
      cancelEdit() {},
      deleteBlock() {},
      editTitle() {},
      saveTitle() {},
      cancelEditTitle() {},
      editCaption() {},
      saveCaption() {},
      cancelEditCaption() {},
      previewArticle() {},
      previewInterview() {},
      previewFlipper() {},
      previewEvent() {},
      previewStory() {},
      previewPhoto() {},
      returnToEdit() {},
      getMainHeroTypeOptions() { return []; },
      getFilteredMainHeroOptions() { return []; },
      selectMainHeroType() {},
      getMainHeroArticleBucketOptions() { return []; },
      selectMainHeroArticleBucket() {},
      saveMainHero() {},
      isManualNewsSelected() { return false; },
      toggleNewsItem() {},
      saveNewsRail() {},
      saveEventCard() {},
      saveCultureInterview() {},
      fetchContentLists() {},
      getAvailableRelatedContentItems() { return []; },
      getSelectedEntityRelatedContent() { return []; },
      getRelatedContentItemLabel(type: string, id: string) { return id; },
      addRelatedContent() {},
      removeRelatedContent() {},
      getPlacementEntityId() { return null; },
      hasPlacementEntityId() { return false; },
      getPlacementMainHeroType() { return null; },
      canSetAsMainHero() { return false; },
      canSetAsEventCard() { return false; },
      canSetAsCultureInterviewBlock() { return false; },
      getCurrentMainHeroSummary() { return ''; },
      getCurrentEventCardSummary() { return ''; },
      isCurrentMainHero() { return false; },
      isCurrentEventCard() { return false; },
      isCurrentCultureInterviewBlock() { return false; },
      syncCurrentMainHeroTitle() {},
      syncCurrentEventCardTitle() {},
      loadLandingPlacements() {},
      updateLandingPlacements() {},
      setAsMainHero() {},
      clearMainHero() {},
      setAsEventCard() {},
      clearEventCard() {},
      setAsCultureInterviewBlock() {},
      clearCultureInterviewBlock() {},
      getCategoryHeroTarget() { return null; },
      canSetAsCultureLandingHero() { return false; },
      canSetAsParisLandingHero() { return false; },
      isCurrentCultureLandingHero() { return false; },
      isCurrentParisLandingHero() { return false; },
      canSetAsCulturePageHero() { return false; },
      canSetAsParisPageHero() { return false; },
      isCurrentCulturePageHero() { return false; },
      isCurrentParisPageHero() { return false; },
      setCultureLandingHero() {},
      clearCultureLandingHero() {},
      setParisLandingHero() {},
      clearParisLandingHero() {},
      setCulturePageHero() {},
      clearCulturePageHero() {},
      setParisPageHero() {},
      clearParisPageHero() {},
      culturePagePlacements: null,
      parisPagePlacements: null,
      saveArticle() {},
      saveInterview() {},
      placements: {
        schemaVersion: 1,
        mainCards: null,
        secondaryCards: null,
        updatedAt: null,
        updatedBy: null,
      },
      mainCardsMode: 'empty',
      selectedMainCardIds: [],
      selectedMainCardIdToAdd: '',
      mainCardsSaving: false,
      mainCardsError: '',
      secondaryCardsMode: 'empty',
      selectedSecondaryCardIds: [],
      selectedSecondaryCardIdToAdd: '',
      secondaryCardsSaving: false,
      secondaryCardsError: '',
      getEventTitle() { return ''; },
      getEventDateLabel() { return ''; },
      getUnselectedMainEventOptions() { return []; },
      getUnselectedSecondaryEventOptions() { return []; },
      addMainCard() {},
      removeMainCard() {},
      moveMainCard() {},
      addSecondaryCard() {},
      removeSecondaryCard() {},
      moveSecondaryCard() {},
      saveMainCards() {},
      saveSecondaryCards() {},
      // --- Culture / Paris Editor defaults ---
      heroOptions: [],
      heroMode: 'empty',
      selectedHeroKey: '',
      heroSaving: false,
      heroError: '',
      featuredInterviewMode: 'auto-latest',
      featuredInterviewSaving: false,
      featuredInterviewError: '',
      leSaviezVousOptions: [],
      leSaviezVousMode: 'auto-latest',
      selectedLeSaviezVousId: '',
      leSaviezVousSaving: false,
      leSaviezVousError: '',
      secondaryStoriesMode: 'auto-latest',
      secondaryStoriesLimit: 3,
      secondaryStoriesSaving: false,
      secondaryStoriesError: '',
      sidebarMode: 'auto-hot',
      sidebarLimit: 4,
      sidebarSaving: false,
      sidebarError: '',
      saveHero() {},
      saveFeaturedInterview() {},
      saveLeSaviezVous() {},
      saveSidebarRail() {},
      saveSecondaryStories() {},
      // --- Event Creator defaults ---
      eventId: null,
      eventForm: {
        startDate: '',
        endDate: '',
        dateType: 'single',
        address: '',
        timeMode: 'none',
        startTime: '',
        endTime: '',
        isMainEvent: false,
        additionalInfo: [],
      },
      setStartDate() {},
      setEndDate() {},
      setDateType() {},
      setTimeMode() {},
      addEventInfo() {},
      removeEventInfo() {},
      setEventInfoIcon() {},
      saveEvent() {},
      deleteEvent() {},
      // --- Article List defaults ---
      hotFilter: 'all',
      matchesFilter() { return true; },
      getVisibleCount() { return 0; },
      // --- Event List defaults ---
      apiBase: '',
      buildApiUrl() { return ''; },
      confirmAndDelete() {},
      handleDeleteClick() {},
      // --- Auth Modal properties ---
      formType: 'login',
      formData: { email: '', password: '', confirmPassword: '', firstName: '', lastName: '' },
      error: '',
      isLoading: false,
      switchTo() {},
      handleSubmit() {},
      // --- Profile Page properties ---
      form: { firstName: '', lastName: '' },
      bookmarks: [],
      bookmarksLoading: false,
      loadedBookmarksForUid: '',
      bookmarkGroups: [],
      refreshBookmarks() {},
      syncBookmarkGroups() {},
      saveChanges() {},
      removeBookmark() {},
      deleteAccount() {},
      // --- Content Actions defaults ---
      contentType: '',
      id: '',
      title: '',
      href: '',
      category: '',
      tag: '',
      imageUrl: '',
      isSharing: false,
      isBookmarking: false,
      bookmark: null,
      isBookmarked: false,
      bookmarkLabel: 'В закладки',
      shareLabel: 'Поделиться',
      buildBookmark() { return null; },
      syncBookmarkState() {},
      syncLabels() {},
      shareContent() {},
      toggleBookmark() {},
      // --- Flipper Creator properties ---
      flipper: {
        title: '',
        lead: '',
        cardLead: '',
        category: '',
        tags: [],
        parisSubCategories: [],
        parisDistrict: '',
        binaryForGuide: false,
        paid: false,
        published: false,
        publishedAt: null,
        carouselContent: [],
        relatedContent: {
          article: [],
          event: [],
          interview: [],
          guide: [],
          news: [],
          flipper: [],
          visualStory: [],
        },
      },
      uploadingIndex: -1,
      addCarouselItem() {},
      removeCarouselItem() {},
      saveFlipper() {},
      deleteFlipper() {},
      // --- Tips Article Creator defaults ---
      addTipsItem() {},
      moveBlock() {},
      handleCoverUpload() {},
      handleItemImageUpload() {},
      uploadingBlockIndex: null,
      // --- Subscription Manager properties ---
      isSubscribed: false,
      subscriptionStatus: '',
      subscriptionEndDate: '',
      createSubscription() {},
      manageSubscription() {},
      // --- Visual Story Creator defaults ---
      story: {
        title: '',
        lead: '',
        cardLead: '',
        imageUrl: '',
        imageCaption: '',
        category: '',
        tags: [],
        parisSubCategories: [],
        parisDistrict: '',
        binaryForGuide: false,
        isHotContent: false,
        paid: false,
        published: false,
        publishedAt: null,
        slides: [],
        relatedContent: {
          article: [],
          event: [],
          interview: [],
          guide: [],
          news: [],
          flipper: [],
          visualStory: [],
        },
        contentCollectionId: null,
      },
      storyId: null,
      uploadingSlideIndex: null,
      addSlide() {},
      removeSlide() {},
      handleSlideImageUpload() {},
      saveStory() {},
      deleteStory() {},
      // --- Photo of the Day Creator defaults ---
      photo: { title: '', imageUrl: '', caption: '', published: false, publishedAt: null },
      photoId: null,
      savePhoto() {},
      deletePhoto() {},
      // --- Landing Editor: Photo of the Day placement ---
      photoOfTheDayOptions: [],
      photoOfTheDayMode: 'auto-latest',
      selectedPhotoOfTheDayId: '',
      photoOfTheDaySaving: false,
      photoOfTheDayError: '',
      savePhotoOfTheDay() {},
    };
  });
}
